apiVersion: v1
kind: Service
metadata:
  name: redmine
  namespace: redmine
  labels:
    app: redmine
    tier: front
spec:
  type: NodePort
  selector:
    app: redmine
    tier: front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
