apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  namespace: database
  labels:
    app: redmine
    tier: sql
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/"
