apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace: database
  labels:
    app: redmine
    tier: sql
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
